spring.application.name=dailyDeals_v6
#spring.datasource.url = jdbc:mysql://localhost:3306/DAILYDEALS
#spring.datasource.username = root
#spring.datasource.password = 2513366Alv
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port = 9191

#Spring actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Azure SQL Server
logging.level.org.hibernate.SQL=DEBUG
spring.datasource.url=jdbc:sqlserver://daily-deals.database.windows.net:1433;database=daily-deals;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=daily-deals
spring.datasource.password=arpit@123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
